# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
  
  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '../src/App/'
    exclude:
      - '../src/App/DependencyInjection/'
      - '../src/App/Entity/'
      - '../src/App/Kernel.php'
        
  FeatureFlag\:
    resource: '../src/FeatureFlag/'
    autowire: true
  
  App\Controller\:
    resource: '../src/App/Controller/'
    tags: [ 'controller.service_arguments' ]

  App\Controller\VerifyAccessConditions:
    arguments:
      $verifier: '@FeatureFlag\Access\Application\VerifyAccessRules'
      
  FeatureFlag\Access\Application\VerifyAccessRules:
    arguments:
      $repository: '@FeatureFlag\Access\Infrastructure\Persistence\FeatureFlagJsonFileRepository'
      
  App\Controller\FeatureFlag\Create:
    arguments:
      $repository: '@FeatureFlag\Access\Infrastructure\Persistence\FeatureFlagJsonFileRepository'
      
  App\Controller\FeatureFlag\Delete:
    arguments:
      $repository: '@FeatureFlag\Access\Infrastructure\Persistence\FeatureFlagJsonFileRepository'
      
  App\Controller\FeatureFlag\Find:
    arguments:
      $repository: '@FeatureFlag\Access\Infrastructure\Persistence\FeatureFlagJsonFileRepository'
  
  App\Controller\FeatureFlag\FindAll:
    arguments:
      $repository: '@FeatureFlag\Access\Infrastructure\Persistence\FeatureFlagJsonFileRepository'
  
  App\Controller\FeatureFlag\Update:
    arguments:
      $repository: '@FeatureFlag\Access\Infrastructure\Persistence\FeatureFlagJsonFileRepository'
  
  FeatureFlag\Access\Infrastructure\Persistence\FeatureFlagJsonFileRepository:
    arguments:
      $path: './../src/feature-flags.json'
  
  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones
